project_name: "external-dns-rackspace-webhook"
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: main.go
    dir: ./cmd/webhook
    binary: external-dns-rackspace-webhook
    goos: ["linux"]
    goarch: ["386", "amd64", "arm64"]
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
    env:
      - CGO_ENABLED=0

universal_binaries:
  - replace: true

archives:
  - formats: ["tar.gz"]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]

sboms:
  - artifacts: archive

dockers:
  - skip_push: false
    use: buildx
    dockerfile: .goreleaser.Dockerfile
    image_templates:
      - ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}-amd64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.description=Rackspace Cloud DNS support for cert-manager
      - --label=org.opencontainers.image.vendor=rackspace
      - --label=org.opencontainers.image.licenses=Apache License 2.0
      - --label=org.opencontainers.image.source=https://rackspace.com/
      - --label=org.opencontainers.image.authors=Rackspace

  - skip_push: false
    goarch: arm64
    use: buildx
    dockerfile: .goreleaser.Dockerfile
    image_templates:
      - ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}-arm64
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.description=Rackspace Cloud DNS support for cert-manager
      - --label=org.opencontainers.image.vendor=rackspace
      - --label=org.opencontainers.image.licenses=Apache License 2.0
      - --label=org.opencontainers.image.source=https://rackspace.com/
      - --label=org.opencontainers.image.authors=Rackspace
docker_manifests:
  - name_template: ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}-arm64
  - name_template: ghcr.io/rackerlabs/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/rackerlabs/{{ .ProjectName }}:{{ .Version }}-arm64

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--oidc-provider=github-actions"
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - --yes

docker_signs:
  - cmd: cosign
    artifacts: manifests
    output: true
    args:
      - "sign"
      - "--oidc-provider=github-actions"
      - "${artifact}@${digest}"
      - --yes