name: release

on:
  push:
    tags:
      - "*" # run on any tag push

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for goreleaser (tags)

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Install syft
        uses: anchore/sbom-action/download-syft@f8bdd1d8ac5e901a77a92f111440fdb1b593736b # v0.20.6

      - name: Install cosign
        uses: sigstore/cosign-installer@d7543c93d881b35a8faa02e8e3605f69b7a1ce62 # v3.10.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chart:
    runs-on: ubuntu-latest
    needs: [container]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push Helm chart
        run: |
          PKG_VER=${GITHUB_REF_NAME#v}

          # update Chart.yaml with tag version
          sed -i \
            -e "s/^appVersion:.*/appVersion: ${PKG_VER}/" \
            -e "s/^version:.*/version: ${PKG_VER}/" \
            charts/Chart.yaml

          sed -i "s/^\([[:space:]]*tag:\).*/\1 ${PKG_VER}/" charts/values.yaml

          # package chart
          helm package -u -d ${{ github.workspace }} charts

          # push chart to ghcr.io
          helm push ${{ github.workspace }}/external-dns-rackspace-${PKG_VER}.tgz \
            oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/charts